HAI 1.2

I IZ PINGING YR 5 MKAY

HOW IZ I PINGING YR BALL
    VISIBLE "PING :{BALL}"
    BALL R DIFF OF BALL AN 1
    DIFFRINT BALL AN 0, O RLY?
        YA RLY, I IZ PONGING YR BALL MKAY
    OIC
IF U SAY SO

HOW IZ I PONGING YR BALL
    VISIBLE "PONG :{BALL}"
    BALL R DIFF OF BALL AN 1
    DIFFRINT BALL AN 0, O RLY?
        YA RLY, I IZ PINGING YR BALL MKAY
    OIC
IF U SAY SO

KTHXBYE
