HAI 1.2

HOW IZ I POW YR N AN YR EXP
    I HAS A RESULT ITZ 1
    IM IN YR LOOP UPPIN YR COUNTR TIL BOTH SAEM COUNTR AN EXP
        RESULT R PRODUKT OF RESULT AN N
    IM OUTTA YR LOOP
    FOUND YR RESULT
IF U SAY SO

VISIBLE I IZ POW YR 2 AN YR 5 MKAY

KTHXBYE
