HAI 1.2

I HAS A FOOTER ITZ "IF U SAY SO:):)VISIBLE I IZ HEADER YR :"::):" AN YR :":::":" AN YR :":::::" MKAY !:)VISIBLE :":::":" !:)VISIBLE I IZ HEADER YR :":::" NEWLINE :::":" AN YR :":::" QUOTE :::":" AN YR :":::" ESCAPE :::":" MKAY !:)VISIBLE :":::":":)VISIBLE FOOTER:):)KTHXBYE"
HOW IZ I HEADER YR NEWLINE AN YR QUOTE AN YR ESCAPE
    SMOOSH "HAI 1.2" NEWLINE "" NEWLINE "I HAS A FOOTER ITZ " QUOTE "IF U SAY SO" ESCAPE ")" ESCAPE ")VISIBLE I IZ HEADER YR " ESCAPE "" QUOTE "" ESCAPE "" ESCAPE ")" ESCAPE "" QUOTE " AN YR " ESCAPE "" QUOTE "" ESCAPE "" ESCAPE "" ESCAPE "" QUOTE "" ESCAPE "" QUOTE " AN YR " ESCAPE "" QUOTE "" ESCAPE "" ESCAPE "" ESCAPE "" ESCAPE "" ESCAPE "" QUOTE " MKAY !" ESCAPE ")VISIBLE " ESCAPE "" QUOTE "" ESCAPE "" ESCAPE "" ESCAPE "" QUOTE "" ESCAPE "" QUOTE " !" ESCAPE ")VISIBLE I IZ HEADER YR " ESCAPE "" QUOTE "" ESCAPE "" ESCAPE "" ESCAPE "" QUOTE " NEWLINE " ESCAPE "" ESCAPE "" ESCAPE "" QUOTE "" ESCAPE "" QUOTE " AN YR " ESCAPE "" QUOTE "" ESCAPE "" ESCAPE "" ESCAPE "" QUOTE " QUOTE " ESCAPE "" ESCAPE "" ESCAPE "" QUOTE "" ESCAPE "" QUOTE " AN YR " ESCAPE "" QUOTE "" ESCAPE "" ESCAPE "" ESCAPE "" QUOTE " ESCAPE " ESCAPE "" ESCAPE "" ESCAPE "" QUOTE "" ESCAPE "" QUOTE " MKAY !" ESCAPE ")VISIBLE " ESCAPE "" QUOTE "" ESCAPE "" ESCAPE "" ESCAPE "" QUOTE "" ESCAPE "" QUOTE "" ESCAPE ")VISIBLE FOOTER" ESCAPE ")" ESCAPE ")KTHXBYE" QUOTE "" NEWLINE "HOW IZ I HEADER YR NEWLINE AN YR QUOTE AN YR ESCAPE" NEWLINE "    SMOOSH "
IF U SAY SO

VISIBLE I IZ HEADER YR ":)" AN YR ":"" AN YR "::" MKAY !
VISIBLE ":"" !
VISIBLE I IZ HEADER YR ":" NEWLINE :"" AN YR ":" QUOTE :"" AN YR ":" ESCAPE :"" MKAY !
VISIBLE ":""
VISIBLE FOOTER

KTHXBYE
